config:
  namespace: Game

GraphicsSettings:
  _flags:
    - not_a_component
    - json_with_keys

  imGuiFont: [string, "assets/fonts/ruda/Ruda-Bold.ttf"]
  gammaCorrection: [float, 2.2]
  shadows: [bool, true]

  debugShadowBoxes: [bool, true]
  debugArmatures: [bool, true]

KeyInputSettings:
  _flags:
    - not_a_component
    - json_with_keys

  retryLevel: [ KeyInput::Key, GLFW_KEY_R ]
  flyCamera: [ KeyInput::Key, GLFW_KEY_F9 ]
  stopFlyingCamera: [ KeyInput::Key, GLFW_KEY_ESCAPE ]

Settings:
  _flags:
    - not_a_component
    - json_with_keys

  graphics: GraphicsSettings
  keyInput: KeyInputSettings
  customSettings: [ json, json::object() ]
