config:
  namespace: Game

AudioSettings:
  _flags:
    - not_a_component
    - json_with_keys

  masterVolume: [ float, 4. ]

GraphicsSettings:
  _flags:
    - not_a_component
    - json_with_keys

  imGuiFont: [string, "assets/fonts/ruda/Ruda-Bold.ttf"]

  gammaCorrection: [float, 2.2]
  msaaSamples: [uint8, 4]
  bloomBlurIterations: [uint8, 3]
  bloomThreshold: [float, 1.7]
  shadows: [bool, true]
  maxArmatureBones: [uint, 64]
  fogStart: [float, 22]
  fogEnd: [float, 28]
  fogEnabled: [bool, true]

  uiPixelScaling: [uint, 3]

  debugShadowBoxes: [bool, true]
  debugArmatures: [bool, true]

KeyInputSettings:
  _flags:
    - not_a_component
    - json_with_keys

  retryLevel: [ KeyInput::Key, GLFW_KEY_R ]
  flyCamera: [ KeyInput::Key, GLFW_KEY_F9 ]
  stopFlyingCamera: [ KeyInput::Key, GLFW_KEY_ESCAPE ]

  moveRight: [ KeyInput::Key, GLFW_KEY_RIGHT ]
  moveLeft: [ KeyInput::Key, GLFW_KEY_LEFT ]
  rotateRight: [ KeyInput::Key, GLFW_KEY_UP ]
  rotateLeft: [ KeyInput::Key, GLFW_KEY_Z ]
  softDrop: [ KeyInput::Key, GLFW_KEY_DOWN ]
  place: [ KeyInput::Key, GLFW_KEY_SPACE ]
  hold: [ KeyInput::Key, GLFW_KEY_C ]

Settings:
  _flags:
    - not_a_component
    - json_with_keys

  graphics: GraphicsSettings
  audio: AudioSettings
  keyInput: KeyInputSettings
  customSettings: [ json, json::object() ]
  limitUpdatesPerSec: [ bool, false ]
  showDeveloperOptions: [ bool, false ]
